import "../lib/i18n";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import i18n from "@/lib/i18n";

// ✅ Use Inter from Google Fonts
const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Diploma Archive",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const currentLang = i18n.language;

	return (
		<html lang={currentLang}>
			<body className={inter.className}>
				{children}
				<Toaster richColors />
			</body>
		</html>
	);
}
